### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by smtabakoglu** [tombstoneghost/TIWAP#2]
Hi guys,
That's what I am seeing while installation.Any idea what to do?

""
root@server TIWAP]# docker-compose up
Pulling db (mongo:4.4)...
Trying to pull repository docker.io/library/mongo ... 
4.4: Pulling from docker.io/library/mongo
7b1a6ab2e44d: Pull complete
90eb44ebc60b: Pull complete
5085b59f2efb: Pull complete
c7499923d022: Pull complete
019496b6c44a: Pull complete
b52e5b3baa61: Pull complete
4737ba38aa64: Pull complete
94c515c55d41: Pull complete
8afc96649890: Pull complete
b19db2567fa7: Pull complete
Digest: sha256:4d7daf5f86a8c17ee456120226d33f35cfbcb57ba49be83fd6b431b4973349d4
Status: Downloaded newer image for docker.io/mongo:4.4
Building app
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'app' failed to build : Build failed

""

Thanks

**Comment by tombstoneghost** [comment]
> 
> 
> Hi guys, That's what I am seeing while installation.Any idea what to do?
> 
> "" root@server TIWAP]# docker-compose up Pulling db (mongo:4.4)... Trying to pull repository docker.io/library/mongo ... 4.4: Pulling from docker.io/library/mongo 7b1a6ab2e44d: Pull complete 90eb44ebc60b: Pull complete 5085b59f2efb: Pull complete c7499923d022: Pull complete 019496b6c44a: Pull complete b52e5b3baa61: Pull complete 4737ba38aa64: Pull complete 94c515c55d41: Pull complete 8afc96649890: Pull complete b19db2567fa7: Pull complete Digest: sha256:4d7daf5f86a8c17ee456120226d33f35cfbcb57ba49be83fd6b431b4973349d4 Status: Downloaded newer image for docker.io/mongo:4.4 Building app unknown flag: --iidfile See 'docker build --help'. ERROR: Service 'app' failed to build : Build failed
> 
> ""
> 
> Thanks

Hey! I think this could be useful. 

`https://stackoverflow.com/questions/67010408/unable-to-start-docker-container-from-docker-compose-unknown-flag-iidfile`

As the issue is with docker-compose version. I tried to install it again on my own system and it worked fine.
